scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_laser
        max_x: 10.
        max_y: 10.
        max_z: 5.
        min_x: -10.
        min_y: -10.
        min_z: -1.
        
        invert: true # activate to remove all points outside of the box